apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ec-{{env}}-{{tenant}}-api
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '5'
spec:
  project: default
  source:
    repoURL: https://github.com/ethio-connect/manifest-repo.git
    targetRevision: main
    path: gitops/workloads/{{tenant}}/api/overlays/{{env}}
  destination:
    server: https://kubernetes.default.svc
    namespace: ec-{{tenant}}-{{env}}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 6
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 40s
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
  info:
    - name: health-probe
      value: readiness=/readyz liveness=/healthz
