apiVersion: batch/v1
kind: Job
metadata:
  name: ec-{{env}}-{{tenant}}-api-migrate
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "4"
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: ghcr.io/ethio-connect/{{tenant}}-api:{{imageTag}}
          command: ["sh", "-c", "npm run db:migrate"]
