/* AUTO-GENERATED by Nx application generator: SVG module declarations. */
/* DO NOT EDIT MANUALLY. Update generator templates or project scaffolding instead. */
declare module "*.svg" {
  import type { FC, SVGProps } from "react";

  const content: string;
  export const ReactComponent: FC<SVGProps<SVGSVGElement>>;
  export default content;
}
