apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ec-env-staging
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: ethio-connect
    ec.environment: staging
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  project: default
  source:
    repoURL: https://github.com/ethio-connect/manifest-repo.git
    targetRevision: main
    path: gitops/argocd/envs/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 6
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 40s
