apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: ExternalSecret
      name: ec-app-runtime-secrets
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: ec-runtime-testing
      - op: replace
        path: /spec/data/0/remoteRef/key
        value: /ethio-connect/testing/database
      - op: replace
        path: /spec/data/1/remoteRef/key
        value: /ethio-connect/testing/redis
      - op: replace
        path: /spec/data/2/remoteRef/key
        value: /ethio-connect/testing/auth
