apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ec-app-runtime-secrets
  namespace: ec-runtime
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: ec-vault-cluster-store
  target:
    name: ec-app-runtime-secrets
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: database_url
      remoteRef:
        key: /ethio-connect/ENV_PLACEHOLDER/database
        property: url
    - secretKey: redis_url
      remoteRef:
        key: /ethio-connect/ENV_PLACEHOLDER/redis
        property: url
    - secretKey: jwt_signing_key
      remoteRef:
        key: /ethio-connect/ENV_PLACEHOLDER/auth
        property: jwt_signing_key
