%%{init: {'theme': 'base', 'themeVariables': { 'fontSize': '20px', 'fontFamily': 'arial' }, 'flowchart': {'nodeSpacing': 50, 'rankSpacing': 50}}}%%
graph TD
    subgraph "Workspace Root"
        direction LR
        subgraph "Nx Monorepo (ethio-connect)"
            direction TB
            subgraph "Apps"
                A[vendor-portal-dashboard]
                B[central-hub-dashboard]
                C[customer-portal-dashboard]
                D[central-hub-api]
                E[customer-portal-api]
                F[vendor-api-server]
            end

            subgraph "Libs"
                G[api-common]
                H[api-features]
                I[ethioconnect]
                J[frontend-features]
                K[ui-components]
            end

            subgraph "CI/CD Pipeline (GitHub Actions)"
                CI_Main("ci.yml - Orchestrator") --> CI_Build("reusable-build-test-lint.yml")
                CI_Main --> CI_Publish("reusable-container-publish.yml")
            end

            CI_Build -->|Lint, Test, Build| GHCR["GHCR (Container Registry)"]
            CI_Publish -->|Build & Push Images| GHCR["GHCR (Container Registry)"]

            A & B & C & D & E & F -->|depends on| G & H & I & J & K
        end

        subgraph "DevOps & Workflows"
            SC("Source Control - GitHub") --> CI_Main
            CI_Publish -->|Updates| GR["GitOps Repo (ethio-connect-manifest)"]
            GHCR -->|Deployment Image| GR
            GR --> ArgoCD("ArgoCD Orchestrator")
        end
    end

    subgraph "Deployment Environments"
        direction TB
        ArgoCD --> P_Cluster["Production Cluster"]
        ArgoCD --> D_Cluster["Development Cluster"]
    end